estimator:
  pickle: model.pickle

strategy:
  name: random
  #params:
  #  seeds: 5

search_space:
  hl1:
    min: 1
    max: 100
    type: int

  hl2:
    min: 0
    max: 100
    type: int

  hl3:
    min: 0
    max: 100
    type: int
  
  l1_reg:
    min: 1e-9
    max: 1e0
    type: float
    warp: log

  l2_reg:
    min: 1e-9
    max: 1e0
    type: float
    warp: log

  learning_rate:
    min: 1e-9
    max: 1e0
    type: float
    warp: log
  
cv:
  name: kfold
  params:
    n_splits: 3
    shuffle: True

dataset_loader:
  name: dsv
  params:
    filenames: idx.csv

trials:
    uri: sqlite:///osprey-trials.db

