estimator:
  pickle: model.pickle

strategy:
  name: sobol
  #params:
  #  seeds: 30

search_space:
  gaussiankernel__sigma:
    min: 1
    max: 1000
    type: float
    warp: log

  kernelridgeregression__l2_reg:
    min: 1e-10
    max: 1e-2
    type: float
    warp: log

cv:
  name: kfold
  params:
    n_splits: 3
    shuffle: True

dataset_loader:
  name: dsv
  params:
    filenames: idx.csv

trials:
    uri: sqlite:///osprey-trials.db

